export enum Routes {
  ONBOARDING = "onboarding",
  LOGIN = "login",
  REGISTER = "register",
  FORGOT_PASSWORD = "forgotPassword",
  NEW_PASSWORD = "newPassword",
  HOME = "home",
  PERSONAL_INFORMATION = "/pledge/personalInformation",
  DONATION_INFORMATION = "/pledge/donationInformation",
  EMERGENCY_CONTACT = "/pledge/emergencyContact",
  MEDICAL_INFORMATION = "/pledge/medicalInformation",
  PLEDGE_ONBOARDING = "/pledge/PledgeOnboarding",
  REVOKE_PLEDGING = "/pledge/revokePledging",
  PLEDGE_CATEGORIES_SUMMARY = "/pledge/pledgeCategoriesSummary",
  NEWS = "news",
}
