export enum Routes {
  ONBOARDING = "onboarding",
  LOGIN = "login",
  REGISTER = "register",
  FORGOT_PASSWORD = "forgotPassword",
  NEW_PASSWORD = "newPassword",
  HOME = "home",
  CHAT = "chat",
  PERSONAL_INFORMATION = "/pledge/personalInformation",
  DONATION_INFORMATION = "/pledge/donationInformation",
  EMERGENCY_CONTACT = "/pledge/emergencyContact",
  MEDICAL_INFORMATION = "/pledge/medicalInformation",
  PLEDGE_ONBOARDING = "/pledge/PledgeOnboarding",
  REVOKE_PLEDGING = "/pledge/revokePledging",
  PLEDGE_CATEGORIES_SUMMARY = "pledgeCategoriesSummary",
  FAQ = "/userProfile/faq",
  USER_PROFILE = "userProfile",
  NEWS = "news",
  ARTICLE_DETAIL = "/news/articleDetail",
  EVENT_DETAIL = "news/eventDetail",
}
